'@type': "SoftwareComponentType"
createdDate: "2017-09-20T14:04:12.037Z"
lastUpdated: "2017-09-20T14:04:52.330Z"
id: "Software.SysconfigEC2"
name: "Sysconfig-EC2"
publishStatus: "PUBLISHED"
publishStatusName: "Published"
schema:
  fields:
  - id: "host"
    label: ""
    description: ""
    dataType:
      type: "ref"
      componentTypeId: "com.vmware.csp.iaas.blueprint.service"
      classId: "Infrastructure.Machine.Schema"
      label: "Machine"
    state:
      dependencies: []
      facets:
      - type: "mandatory"
        value:
          type: "constant"
          value:
            type: "boolean"
            value: true
      - type: "internal"
        value:
          type: "constantClause"
          value:
            type: "boolean"
            value: true
      - type: "visible"
        value:
          type: "constantClause"
          value:
            type: "boolean"
            value: false
    isMultiValued: false
containerFieldId: "host"
lifecycleTasks:
- createdDate: "2017-09-20T14:04:12.038Z"
  lastUpdated: "2017-09-20T14:04:12.038Z"
  script:
    scriptContent: "#!/bin/bash\nsudo su\nsetenforce 0\n/sbin/chkconfig iptables off\n\
      /sbin/chkconfig ip6tables off\n/sbin/service iptables stop\n/sbin/service ip6tables\
      \ stop"
    isRebootAfter: false
    scriptTypeId: "Bash"
  taskDescriptorRef:
    id: "INSTALL"
    label: "Install"
