'@type': "SoftwareComponentType"
createdDate: "2017-05-04T02:50:10.069Z"
lastUpdated: "2017-05-07T13:14:43.310Z"
id: "Software.SystemConfiguration"
name: "System Configuration"
publishStatus: "PUBLISHED"
publishStatusName: "Published"
schema:
  fields:
  - id: "host"
    label: ""
    description: ""
    dataType:
      type: "ref"
      componentTypeId: "com.vmware.csp.iaas.blueprint.service"
      classId: "Infrastructure.Machine.Schema"
      label: "Machine"
    state:
      dependencies: []
      facets:
      - type: "mandatory"
        value:
          type: "constant"
          value:
            type: "boolean"
            value: true
      - type: "internal"
        value:
          type: "constantClause"
          value:
            type: "boolean"
            value: true
      - type: "visible"
        value:
          type: "constantClause"
          value:
            type: "boolean"
            value: false
    isMultiValued: false
containerFieldId: "host"
lifecycleTasks:
- createdDate: "2017-05-04T02:50:10.069Z"
  lastUpdated: "2017-05-07T13:14:43.310Z"
  script:
    scriptContent: "#!/bin/bash\n/sbin/chkconfig iptables off\n/sbin/chkconfig ip6tables\
      \ off\n/sbin/service iptables stop\n/sbin/service ip6tables stop"
    isRebootAfter: false
    scriptTypeId: "Bash"
  taskDescriptorRef:
    id: "INSTALL"
    label: "Install"
